### ISSUE TITLE
Update to latest version of Godot 4

### ISSUE THREAD

**Issue by Zakarya1000** [gdquest-demos/godot-4-3d-third-person-controller#20]
Changes have been made in Godot 4 so that this project doesn't work in the latest version of Godot.

**Comment by tung-nt-niteco** [comment]
Yeah, there are a couple of things to change, including this one:
https://github.com/gdquest-demos/godot-4-3d-third-person-controller/issues/18

Then,
set_target_location -> set_target_position
get_next_location -> get_next_path_position

It worked for me after all.

**Comment by NathanLovato** [comment]
The project is running fine for our team in Godot 4.0.2, the latest stable version. There are no instances of get_next_location() or set_target_location() in the source code. Did you guys pull the latest changes? It sounds like you might have downloaded an older copy of the source code.

**Comment by NathanLovato** [comment]
Thanks, closing for now as it seems to be working fine around the team. I invite you to re download the code to get the latest version, and if it fails to open please let me know and we'll reopen the issue.

**Comment by NathanLovato** [comment]
Thanks for mentioning this, I'll update the link!

**Comment by BillyJoelsNightmareExplosion** [comment]
> Thanks for mentioning this, I'll update the link!

Hey just to let you know @NathanLovato, the download link on the site still points to an older version.

**Comment by Starzky** [comment]
On v4.1.3.stable.official [f06b6836a], the player drops straight through the terrain - progressively, until falling straight out of the bottom of the ground.
