### ISSUE TITLE
Parser Error: Cannot infer the type of "next_location" variable because the value doesn't have a set type.

### ISSUE THREAD

**Issue by brandbrilliance** [gdquest-demos/godot-4-3d-third-person-controller#34]
This error occurs on the latest download from the package on MacOS. 

Anyone know how do you fix this type error?

Line 39:Cannot infer the type of "next_location" variable because the value doesn't have a set type.
Line 42:Cannot infer the type of "direction" variable because the value doesn't have a set type.

```gdscript
39		var next_location := _navigation_agent.get_next_location() // *** RED
		
		if not _navigation_agent.is_target_reached():
42			var direction := (next_location - global_position) // *** RED
			direction.y = 0
			direction = direction.normalized()

```

**Comment by brandbrilliance** [comment]
Duplicate of #23

**Comment by GigglingGalaxy** [comment]
location -> position
