### ISSUE TITLE
Known issue: beetle animations are broken in beta 17

### ISSUE THREAD

**Issue by NathanLovato** [gdquest-demos/godot-4-3d-third-person-controller#5]
EDIT: the project was updated to beta 17 in #13 

Now, most animations work fine. Only the beetle's animation tree doesn't play well.

----------------------

In Godot 4 beta 10 animations don't work properly, Godot's throwing this error:

![image](https://user-images.githubusercontent.com/12694995/209450812-2ce7121c-a7b5-4c27-a42b-3738bb1d99f8.png)

EDIT: this error is fixed, but animations still don't work as intended. We recommend using beta 7/8 until this is fixed

**Comment by TokageItLab** [comment]
It is caused by trying to travel to a state `play_idle` that does not exist in `bee_root.gd`.

I will consider changing state machine to throw a clear error when traveling to a non-existent state in core later.

**Comment by NathanLovato** [comment]
Thanks, it does solve this one error, and a more precise error message would be great. Animation tree state changes still don´t work in the game, but I'll see if it can be fixed.

**Comment by NathanLovato** [comment]
After some fiddling, I'm unsure if it's an issue on our side or if there's an issue on Godot's side. The animation state machine graph we've used so far, with simple transitions using default properties, doesn't work anymore: AnimationNodeStateMachinePlayback.travel() doesn't seem to manage to travel to various states, and aside from setting some states to auto-advance, I couldn't get the others to work properly.

If anyone has an idea or time to look into it, help would be much appreciated.

**Comment by TokageItLab** [comment]
Maybe related https://github.com/godotengine/godot/issues/70536#issuecomment-1364710796

**Comment by NathanLovato** [comment]
It seems like it, thanks much @TokageItLab!

**Comment by SaracenOne** [comment]
@NathanLovato Looking into this. You wouldn't happen to have any examples of this would you? I have one MRP, but it seems to indicate issues with the `_process_graph` rather than the transitions, which I can't seem to replicate.

**Comment by TokageItLab** [comment]
Okay I sent https://github.com/godotengine/godot/pull/70576 for path checking.

Also I sent https://github.com/godotengine/godot/pull/70572 to fix a bug which is StateMachine's fading isn't finish correctly, please can you check it? It would be helpful to know if it will make your project correct.

**Comment by NathanLovato** [comment]
@TokageItLab I'll build with your PR and test now

@SaracenOne If Tokage's fix doesn't solve the issue I'll make an MRP for you

**Comment by NathanLovato** [comment]
https://github.com/godotengine/godot/pull/70572 does help, thanks!

**Comment by NathanLovato** [comment]
Mostly fixed in [8353148](https://github.com/gdquest-demos/godot-4-3d-third-person-controller/commit/8353148e09d9117a303d1df49c98b582c6d1ff33)

Only the beetle's animation tree doesn't work. @gtibo would you be able to fix or remake the beetle's anim tree? Godot 4 is getting to release candidate now, it should be relatively stable at this point.

**Comment by NathanLovato** [comment]
Fixed in latest RC
